# Generated by Django 3.0.8 on 2021-10-29 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
